//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_TEST.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ASP.NET_TEST.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 110000	北京市			北京市
        ///110100	北京市	市辖区		北京市市辖区
        ///110101	北京市	市辖区	东城区	北京市市辖区东城区
        ///110102	北京市	市辖区	西城区	北京市市辖区西城区
        ///110103	北京市	市辖区	崇文区	北京市市辖区崇文区
        ///110104	北京市	市辖区	宣武区	北京市市辖区宣武区
        ///110105	北京市	市辖区	朝阳区	北京市市辖区朝阳区
        ///110106	北京市	市辖区	丰台区	北京市市辖区丰台区
        ///110107	北京市	市辖区	石景山区	北京市市辖区石景山区
        ///110108	北京市	市辖区	海淀区	北京市市辖区海淀区
        ///110109	北京市	市辖区	门头沟区	北京市市辖区门头沟区
        ///110111	北京市	市辖区	房山区	北京市市辖区房山区
        ///110112	北京市	市辖区	通州区	北京市市辖区通州区
        ///110113	北京市	市辖区	顺义区	北京市市辖区顺义区
        ///110114	北京市	市辖区	昌平区	北京市市辖区昌平区
        ///110115	北京市	市辖区	大兴区	北京市市辖区大兴区
        ///110116	北京市	市辖区	怀柔区	北京市市辖区怀柔区
        ///110117	北京市	市辖区	平 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TextFile {
            get {
                return ResourceManager.GetString("TextFile", resourceCulture);
            }
        }
    }
}
